### ISSUE TITLE
Wrong Schema used?!

### ISSUE THREAD

**Issue by goern** [thoth-station/result-api#307]
**Describe the bug**
Schema used by adivsor and result-api seems out of sync

**To Reproduce**
1. do a 'thamos advise'

```

172.54.46.1 - - [17/Dec/2019:09:46:32 +0000] "POST /api/v1/adviser-result HTTP/1.1" 500 290 "-" "python-requests/2.22.0"
--
  | 2019-12-17 09:46:33,382 [26] ERROR    thoth.result_api:1891: Exception on /api/v1/adviser-result [POST]
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 99, in store_document
  | self.SCHEMA(document)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 272, in __call__
  | return self._compiled([], data)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
  | return base_validate(path, iteritems(data), out)
  | File "/opt/app-root/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
  | raise er.MultipleInvalid(errors)
  | voluptuous.error.MultipleInvalid: extra keys not allowed @ data['metadata']['thoth_deployment_name']
  | The above exception was the direct cause of the following exception:
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
  | response = self.full_dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
  | rv = self.handle_user_exception(e)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
  | reraise(exc_type, exc_value, tb)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/app-root/src/wsgi.py", line 60, in post_adviser_result
  | document_id = adapter.store_document(request.json)
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 101, in store_document
  | raise SchemaError("Failed to validate document schema") from exc
  | thoth.storages.exceptions.SchemaError: Failed to validate document schema
```

**Comment by fridex** [comment]
The issue is caused by missing release `thoth-storages==0.19.28` that was not successful.

[1] https://github.com/thoth-station/storages/issues/1380#issuecomment-563212470
[2] https://pypi.org/project/thoth-storages/#history

**Comment by fridex** [comment]
The issue was in the markup language used in the README file - PyPI refused to publish artifact. I've released new `thoth-storages`. Let's wait for bots to verify and populate updates to repos.

**Comment by fridex** [comment]
Update populated, new result-api in test and stage. Tested advises, they work. Thanks for the report, feel free to reopen if the issue persists.
